export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const FINISH_AJAX_CALL = 'FINISH_AJAX_CALL';

export const SET_ERROR_OBJECT = '[ERROR HANDLER] SET ERROR OBJECT';

export const FETCH_TEST_SUITE_DETAILS = '[TEST CASE EXECUTION] FETCH TEST SUITE DETAILS';
export const FETCH_TEST_SUITE_DETAILS_SUCCESS = '[TEST CASE EXECUTION] FETCH TEST SUITE DETAILS SUCCESS';
export const FETCH_TEST_SUITE_RESULTS = '[TEST CASE EXECUTION] FETCH TEST SUITE RESULTS';
export const FETCH_TEST_SUITE_RESULTS_SUCCESS = '[TEST CASE EXECUTION] FETCH TEST SUITE RESULTS SUCCESS';
