export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const FINISH_AJAX_CALL = 'FINISH_AJAX_CALL';

export const SET_ERROR_OBJECT = '[ERROR HANDLER] SET ERROR OBJECT';

export const FETCH_CASE_TYPE = '[JUDICATURE] FETCH CASE TYPE';
export const FETCH_CASE_TYPE_SUCCESS = '[JUDICATURE] FETCH CASE TYPE SUCCESS';
export const FETCH_COURT_CASE = '[JUDICATURE] FETCH COURT CASE';
export const FETCH_COURT_CASE_SUCCESS = '[JUDICATURE] FETCH COURT CASE SUCCESS';
